const PROTOCOL_VERSION = 1;
const HEADER_SIZE = 42;

// Standard Opcodes
const OPCODES = {
  HANDSHAKE_INIT: 0x01,
  HANDSHAKE_ACK: 0x02,
  PEER_ANNOUNCE: 0x10,
  PEER_OFFLINE: 0x11,
  CHAT_MESSAGE: 0x20,
  FILE_OFFER: 0x30,
  FILE_ACCEPT: 0x31,
  FILE_REJECT: 0x32,
  FILE_CHUNK: 0x33,
  FILE_COMPLETE: 0x34
};

module.exports = {
  PROTOCOL_VERSION,
  HEADER_SIZE,
  OPCODES
};
